spring.application.name=demo

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/6cfa456d-2478-45eb-ae8e-77374e84ab06/discovery/v2.0/keys
# Cambia esta línea para que coincida con el claim 'aud' exacto del token:
spring.security.oauth2.resourceserver.jwt.audiences=d7bf9b88-3887-46c7-8493-6cc9c9867046