spring.application.name=demo
# spring.cloud.azure.active-directory.credential.client-id=${AZURE_CLIENT_ID}
# spring.cloud.azure.active-directory.tenant-id=${AZURE_TENANT_ID}
# pring.cloud.azure.active-directory.app-id-uri=${AZURE_APP_ID_URI}

# Configuración estándar de Spring Security OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=${AZURE_APP_ID_URI}